doap: small update
My @gnome.org email address no longer works.
I think it's the gnome:userid which is more important.

Put stefkost in comment because of the following git push error
message:
```
remote: ERROR: gtk-doc.doap is not valid:
remote: Invalid gnome:userid property (stefkost is not a member of the gnomecvs group)
```