Meson: check for parameterized python module when tests are enabled
Several tests require the 'parameterized' python module.

If it is not present the following error occurs:

```
ModuleNotFoundError: No module named 'parameterized'
```

So check at build time the requirements.